
services:
  wings.examples.usecase.server:
    image: ${DOCKER_REGISTRY-}wingsexamplesusecaseserver
    build:
      context: .
      dockerfile: Examples/UseCase/Wings.Examples.UseCase.Server/Dockerfile
  mysql-db:
    container_name: mysql-docker        # 指定容器的名称
    image: mysql:8.0                   # 指定镜像和版本
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_ROOT_HOST: ${MYSQL_ROOT_HOST}
    volumes:
      - "${MYSQL_DIR}/data:/var/lib/mysql"           # 挂载数据目录
      - "${MYSQL_DIR}/config:/etc/mysql/conf.d"      # 挂载配置文件目录